In [1]:
import requests
import pandas as pd
#load .env variables
import os
from dotenv import load_dotenv
load_dotenv()
PWD = os.getenv('PWD')
import sys
sys.path.insert(1, PWD)

endpoint = 'http://192.168.1.125:8000'

In [2]:
PWD

'C:\\Users\\akorz\\Documents\\binance_bot\\binance_candle_plot'

In [3]:
from data_API.data_API_wrapper import DataApiWrapper
# or use wrapper to get data from dataAPI
w = DataApiWrapper(
    endpoint=endpoint
)
print(f'MA_lines: {w.get_ma_lines()}')
print('Stock data:')
display(w.get_stock_data())
print('Trade data:')
display(w.get_trade_data())

MA_lines: (1, 2, 5, 100)
Stock data:

                   Date     Open     High      Low    Close      Real_Date
0   2022-03-15 12:26:00  0.04851  0.04851  0.04843  0.04844  1647336360000
1   2022-03-15 12:27:00  0.04845  0.04848  0.04843  0.04843  1647336420000
2   2022-03-15 12:28:00  0.04842  0.04844  0.04842  0.04842  1647336480000
3   2022-03-15 12:29:00  0.04842  0.04844  0.04842  0.04844  1647336540000
4   2022-03-15 12:30:00  0.04844  0.04871  0.04844  0.04870  1647336600000
..                  ...      ...      ...      ...      ...            ...
195 2022-03-15 15:41:00  0.04889  0.04889  0.04886  0.04886  1647348060000
196 2022-03-15 15:42:00  0.04886  0.04886  0.04884  0.04884  1647348120000
197 2022-03-15 15:43:00  0.04887  0.04890  0.04885  0.04889  1647348180000
198 2022-03-15 15:44:00  0.04889  0.04892  0.04889  0.04889  1647348240000
199 2022-03-15 15:45:00  0.04887  0.04888  0.04886  0.04886  1647348300000

[200 rows x 6 columns]

Trade data:

,type,sell_price,buy_price,fee,RVN,USD,_amount,timestamp,reason
0,buy,NaN,0.04891,0.1,100,0.000000,0,NaT,trade_alg
1,sell,0.04889,0.04891,0.1,0,4.884111,100,NaT,trade_alg

In [4]:
df = w.get_stock_data()
for col in ['open_', 'high_', 'low_', 'close_']:
    df[col]=df[col].map('{:.4f}'.format)

df.loc[:, ['open_', 'high_', 'low_', 'close_','open_time', 'close_time', ]]
# df

KeyError: 'open_'

In [ ]:
td = w.get_trade_data()
for col in ['sell_price', 'buy_price', ]:
    td[col]=td[col].map('{:.4f}'.format)
for col in ['RVN', 'USD', '_amount']:
    td[col]=td[col].map('{:.1f}'.format)
# td['timestamp'] = pd.to_datetime(td["timestamp"].dt.strftime('%Y-%m-%d %h'))
# td.loc[:, ['open_', 'high_', 'low_', 'close_','open_time', 'close_time', ]]
td